config/routes.rb
Rails.application.routes.draw do
  # move omniauth_callbacks devise module out the scope ':locale' when use it
  # devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  # use it when you add a new language to site
  # scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do

  constraints(RootStoreRoutes) do
    get '/', to: 'stores#show'
  end
  
  constraints(!RootStoreRoutes) do
    get '/', to: 'home#landing_page', as: :root
  end

  devise_for :users,
    controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
    },
    :path => "/",
    :path_names => { :sign_in =>       'login',
                     :sign_out =>      'logout',
                     :sign_up =>       '',
                     :registration =>  'register',
                     :edit =>          'profile',
                     :cancel =>        'cancel',
                     :confirmation =>  'verification'
                    }

  get "/profile", to: "users/registrations#edit", as: :profile
  put "/profile", to: "users/registrations#update"
  
  namespace :dashboard do
    root 'main#index', as: :dashboard
    get '/ajax/report', to: "main#report"

    resources :products, except: [:destroy]
    resources :pages, except: [:show, :destroy] do
      member do 
        put 'publish'
        put 'unpublish'
      end
    end

    resources :categories, except: [:show, :destroy] do
      member do 
        put 'hide'
        put 'unhide'
      end
    end

    resources :reviews, except: [:show, :destroy, :create] do
      member do 
        put 'hide'
        put 'unhide'
      end
    end

    resources :users, except: [:show, :destroy, :create] do 
      member do 
        put 'ban'
        put 'unban'
      end
    end
    resources :orders, except: [:destroy, :create]

    get :me, to: "users#me"
    put :me, to: "users#update_me" 

    scope :setup do 
      get :social_media, to: 'setup_stores#social_media'
      get :analytics,  to: 'setup_stores#analytics'
      get :details,  to: 'setup_stores#details'
      get :domain,  to: 'setup_stores#domain'
      get :seo,  to: 'setup_stores#seo'
      get :design, to: 'setup_stores#design'
      get :configuration, to: 'setup_stores#configuration'
      get :subscription, to: 'setup_stores#subscription'
      put :social_media, to: 'setup_stores#update_social_media'
      put :analytics, to: 'setup_stores#update_analytics'
      put :details, to: 'setup_stores#update_details'
      put :domain,  to: 'setup_stores#update_domain'
      put :seo,  to: 'setup_stores#update_seo'
      put :design, to: 'setup_stores#update_design'
      put :configuration, to: 'setup_stores#update_configuration'
      post :subscription, to: 'setup_stores#upgrade_subscription'
    end
  end

  # Sitemap
  resources :sitemap, only: [:index]
  
  resources :reviews
  resources :locations, except: [:show]
  resources :cart_items do
     member do 
      post 'decrease'
      post 'increase'
     end
  end
  
  resources :orders do 
    member do 
      put 'cancel'
    end
  end

  # Cart
  get 'cart' => "cart#index"

  # Search
  get '/search' => "search#search"

  # Contact Us 
  post '/p/contact-us', to: "contacts#create", as: :contact_us
  get '/p/contact-us', to: "contacts#new", as: :contacts

  # Dynamic pages
  get "/p/:slug", :to => "page#show"
  
  # Products
  get '/products/:category_slug/:id' => 'products#show', as: :product
  get '/products/:category_slug/' => 'products#index', as: :product_category
  get '/products' => 'products#index', as: :products

  # Favorites route
  post "products/:product_id/favorite" => "favorites#create", :as => :favorite
  delete "favorites/:product_id/destroy" => "favorites#destroy", :as => :destroy_favorite
  get '/favorites',to: "favorites#index",as: :favorites
  
  # admin
  namespace :admin do
    root 'dashboard#index'
    resources :users, except: [:destroy] do
      member do
        get :orders
        put :ban
        put :unban
      end
    end
    resources :categories, except: [:destroy]
    resources :products, except: [:destroy]
    resources :product_offers, except: [:destroy]
    resources :orders, only: [:index, :edit, :update, :show]
    resources :contacts, only: [:index]
    resources :pages, except: [:show]
    resources :reviews, only: [:index, :edit, :update]
  end

  # Errors 
  get "/404", :to => "errors#not_found"
  get "/403", :to => "errors#unavailable"
  get "/500", :to => "errors#internal_server_error"
  

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api/graphql"
  end

  # API 
  namespace :api do
    post "/graphql", to: "graphql#execute"
    post "/Settings.telegram.token" => 'telegram_bot#webhook'
  end

  # All paths with no locale specified will be redirected to the same paths with default locale
  #root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  #get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  #get '*path', :to => 'errors#not_found', via: :all
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < Admin::AdminController
  before_action :set_review, except: [:create, :new, :index]


  def index
    @reviews = Review.order(created_at: :desc).page params[:page]
  end

  def edit
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to admin_reviews_url, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  private


  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find params[:id]
  end

  def review_params
    params.require(:review).permit(:id, :user_id, :product_id ,:rate, :content, :hidden)
  end
end

app/controllers/dashboard/reviews_controller.rb
class Dashboard::ReviewsController < StoreBaseController
  before_action :authenticate_user!, :check_authorization
  before_action :set_review, only: [:edit, :hide, :unhide, :update]
  respond_to :html

  def index
    @pagy, @reviews = pagy(MarketPlace::Dashboard::Review.index(@options)[:reviews])
  end

  def edit
  end

  def update
    MarketPlace::Dashboard::Review.update(@review, review_params, @options)
    flash[:notice] = 'تم تعديل التقييم بنجاح.'
    redirect_to dashboard_reviews_url
  rescue MarketPlace::Errors::UnprocessableEntity
    render :edit
  end

  def hide
    @review.update(hidden: true)
  end

  def unhide
    @review.update(hidden: false)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = @current_store.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:id, :hidden, :content)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < StoreBaseController
  before_action :authenticate_user!, :set_product

  def create
    if @product && !current_user.reviews.map(&:product_id).include?(@product.id)
      @review = @current_store.reviews.new(review_params)
      @review.user = current_user
      @review.save
    else
      # raise error here
    end
  end

  private 

  # Never trust parameters from the scary internet, only allow the white list through.
  def review_params
    params.require(:review).permit(:user_id, :rate, :content, :product_id)
  end

  def set_product
    @product = @current_store.products.find(review_params[:product_id])
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def print_review_status(status)
    if status
      "<i class='fa fa-eye-slash' title='مخفي'></i>".html_safe
    else
      "<i class='fa fa-eye'></i>".html_safe
    end
  end 
end

app/views/admin/reviews/_form.html.erb
<%= form_for([:admin, @review], html: { class: 'form-horizontal review' } ) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title"><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
      </div>
      <div class="panel-body">
        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :rate,  class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :rate, max: 5, min: 1, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :content, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :hidden, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :hidden %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :deleted, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :deleted %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/reviews/_review.html.erb
<tr>
  <td>
    <%= link_to edit_admin_user_path(review.user)  do %>
      <%= review.user.fullname %> <i class="fa fa-user"></i>
    <% end %>
  </td>
  <td>
    <%= link_to  edit_admin_product_path(review.product) do  %>
      <%= image_tag review.product.image.small.url, class: "cat_img"  %>
      <%= review.product.ar_name %>
    <% end %>
  </td>
  <td><%= review.content %></td>
  <td><%= review.rate %></td>
  <td><span class="label <%= !review.hidden ? 'bg-green' : 'bg-red' %>"><%= review.hidden %></span></td>
  <td><span class="label <%= !review.deleted ? 'bg-green' : 'bg-red' %>"><%= review.deleted %></span></td>
  <td>
    <%= link_to "Edit", edit_admin_review_path(review.id) %>
  </td>
</tr>

app/views/admin/reviews/edit.html.erb
<section class="content-header">
  <h1>
    Editing Review #<%= @review.id %>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= admin_root_path %>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="<%= admin_reviews_path %>"><i class="fa fa-tags"></i> Review</a></li>
    <li class="active">Editing #<%= @review.id %></li>
  </ol>
</section>


<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <%= render 'shared/bootstrap_alert' %>
      <div class="box">
        <div class="box-body">
          <%= render 'form' %>
        </div>
      </div>
    <%= link_to 'Back', admin_reviews_path, class: 'btn btn-default' %>
    </div>
  </div>
</section>

app/views/admin/reviews/index.html.erb
<section class="content-header">
  <h1>
    Reviews
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= admin_root_path %>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Reviews</li>
  </ol>
</section>


<section class="content">
  <!-- /.row -->
  <div class="row">
    <div class="col-xs-12">
      <%= render 'shared/bootstrap_alert' %>
      <div class="box">
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tbody>
              <tr>
                <th>User</th>
                <th>Product</th>
                <th>Content</th>
                <th>Star</th>
                <th>Hidden</th>
                <th>Deleted</th>
                <th></th>
              </tr>
              <%= render @reviews %>
            </tbody>
          </table>
          <div class="text-center">
            <%= paginate @reviews %>
          </div>

        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
  </div>
</section>