config/routes.rb
Rails.application.routes.draw do
  # move omniauth_callbacks devise module out the scope ':locale' when use it
  # devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  # use it when you add a new language to site
  # scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do

  constraints(RootStoreRoutes) do
    get '/', to: 'stores#show'
  end
  
  constraints(!RootStoreRoutes) do
    get '/', to: 'home#landing_page', as: :root
  end

  devise_for :users,
    controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
    },
    :path => "/",
    :path_names => { :sign_in =>       'login',
                     :sign_out =>      'logout',
                     :sign_up =>       '',
                     :registration =>  'register',
                     :edit =>          'profile',
                     :cancel =>        'cancel',
                     :confirmation =>  'verification'
                    }

  get "/profile", to: "users/registrations#edit", as: :profile
  put "/profile", to: "users/registrations#update"
  
  namespace :dashboard do
    root 'main#index', as: :dashboard
    get '/ajax/report', to: "main#report"

    resources :products, except: [:destroy]
    resources :pages, except: [:show, :destroy] do
      member do 
        put 'publish'
        put 'unpublish'
      end
    end

    resources :categories, except: [:show, :destroy] do
      member do 
        put 'hide'
        put 'unhide'
      end
    end

    resources :reviews, except: [:show, :destroy, :create] do
      member do 
        put 'hide'
        put 'unhide'
      end
    end

    resources :users, except: [:show, :destroy, :create] do 
      member do 
        put 'ban'
        put 'unban'
      end
    end
    resources :orders, except: [:destroy, :create]

    get :me, to: "users#me"
    put :me, to: "users#update_me" 

    scope :setup do 
      get :social_media, to: 'setup_stores#social_media'
      get :analytics,  to: 'setup_stores#analytics'
      get :details,  to: 'setup_stores#details'
      get :domain,  to: 'setup_stores#domain'
      get :seo,  to: 'setup_stores#seo'
      get :design, to: 'setup_stores#design'
      get :configuration, to: 'setup_stores#configuration'
      get :subscription, to: 'setup_stores#subscription'
      put :social_media, to: 'setup_stores#update_social_media'
      put :analytics, to: 'setup_stores#update_analytics'
      put :details, to: 'setup_stores#update_details'
      put :domain,  to: 'setup_stores#update_domain'
      put :seo,  to: 'setup_stores#update_seo'
      put :design, to: 'setup_stores#update_design'
      put :configuration, to: 'setup_stores#update_configuration'
      post :subscription, to: 'setup_stores#upgrade_subscription'
    end
  end

  # Sitemap
  resources :sitemap, only: [:index]
  
  resources :reviews
  resources :locations, except: [:show]
  resources :cart_items do
     member do 
      post 'decrease'
      post 'increase'
     end
  end
  
  resources :orders do 
    member do 
      put 'cancel'
    end
  end

  # Cart
  get 'cart' => "cart#index"

  # Search
  get '/search' => "search#search"

  # Contact Us 
  post '/p/contact-us', to: "contacts#create", as: :contact_us
  get '/p/contact-us', to: "contacts#new", as: :contacts

  # Dynamic pages
  get "/p/:slug", :to => "page#show"
  
  # Products
  get '/products/:category_slug/:id' => 'products#show', as: :product
  get '/products/:category_slug/' => 'products#index', as: :product_category
  get '/products' => 'products#index', as: :products

  # Favorites route
  post "products/:product_id/favorite" => "favorites#create", :as => :favorite
  delete "favorites/:product_id/destroy" => "favorites#destroy", :as => :destroy_favorite
  get '/favorites',to: "favorites#index",as: :favorites
  
  # admin
  namespace :admin do
    root 'dashboard#index'
    resources :users, except: [:destroy] do
      member do
        get :orders
        put :ban
        put :unban
      end
    end
    resources :categories, except: [:destroy]
    resources :products, except: [:destroy]
    resources :product_offers, except: [:destroy]
    resources :orders, only: [:index, :edit, :update, :show]
    resources :contacts, only: [:index]
    resources :pages, except: [:show]
    resources :reviews, only: [:index, :edit, :update]
  end

  # Errors 
  get "/404", :to => "errors#not_found"
  get "/403", :to => "errors#unavailable"
  get "/500", :to => "errors#internal_server_error"
  

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api/graphql"
  end

  # API 
  namespace :api do
    post "/graphql", to: "graphql#execute"
    post "/Settings.telegram.token" => 'telegram_bot#webhook'
  end

  # All paths with no locale specified will be redirected to the same paths with default locale
  #root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  #get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  #get '*path', :to => 'errors#not_found', via: :all
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id                     :integer          not null, primary key
#  user_id                :integer
#  location_id            :integer    
#  order_cart_id          :integer
#  latitude               :float
#  longitude              :float
#  status                 :integer
#  payment_method         :string
#  detail                 :text
#  admin_detail           :text
#  created_at             :datetime         not null
#  updated_at             :datetime         not null

#  Indexes
#  add_index :orders, :user_id
#  add_index :orders, :store_id
#  add_index :orders, :location_id

class Order < ApplicationRecord
  POSSIBILE_STATUS = ['cancelled', 'completed', 'executing']
  PAYMENT_METHODS = ['cash_on_delivery', 'paypal', 'credit_card']

  after_initialize :set_default_status, :if => :new_record?

  has_many :items, class_name: 'OrderItem', dependent: :destroy
  belongs_to :user, optional: true
  belongs_to :store, counter_cache: true
  belongs_to :location
  
  enum status: [:executing, :completed, :cancelled]
  scope :executing_orders,  -> {where(status: 0)}
  scope :completed_orders, -> {where(status: 1)}
  scope :cancelled_orders, -> {where(status: 2)}


  scope :today, ->{where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now))}
  scope :week,->{where(:created_at => (Time.zone.now.beginning_of_week..Time.zone.now))}
  scope :month,->{where(:created_at => (Time.zone.now.beginning_of_month..Time.zone.now))}
  scope :yesterday, ->{where(:created_at => (Time.zone.now.beginning_of_day-1.day..Time.zone.now.beginning_of_day))}
  scope :prev_month,->{where(:created_at =>((Time.now.beginning_of_month-1.day)..Time.zone.now.beginning_of_month))}
  scope :three_month,->{where(:created_at =>((Time.zone.now-3.month).beginning_of_month..Time.zone.now.beginning_of_month))}


  def price
    items.sum {|item| item.price * item.quantity} 
  end

  def total_price
    price + delivery_price
  end

  def total_item
    items.sum[:quantity]
  end

  def empty?
    items.count == 0 
  end

  def delivery_price
    return 0 if price == 0 ||  price >= 25000
    return 3000 if price < 25000
  end

  def as_json(options={})
    attrs = [:id, :details]
    super(only: attrs, include: { 
      items: { only: [:quantity], include: { product: { only: [:id, :name, :description, :price ],  methods: [:image_url] } } } 
    })
  end 

  def add_items_from_cart(cart)
    cart.items.each do |item|
      unless item.product.is_infinite?
        item.product.in_stack -= item.quantity > item.product.in_stack ?  item.product.in_stack :  item.quantity
        item.product.save
      end 
      items.create!(
        store_id: item.store_id,
        product_id: item.product_id,
        order_id: item.order_id,
        cart_id: cart.id,
        quantity: item.quantity,
        price: item.price
      )
      item.destroy
    end 
  end

  def cancel_order
    return if executing? && (Time.now < created_at + 5.minute)
    cancelled!
    items.each do |item|
      item.product.in_stack += item.quantity
      item.product.save
    end 
  end

  def set_default_status
    self.status ||= :executing
  end

  def change_order_status_email
    ::Notifier.send("#{status}_order_message", order).deliver_later!
  end

  def telegram_message
    message = []
    message << "طلب جديد قد تم إضافته: ##{id}"
    message << "الرابط على الموقع: #{Settings.host}/admin/orders/#{id}"
    message << "التقاصيل:"

    items.each do |item|
      message << "#{items.index(item) + 1}- #{item.product.ar_name} ( X #{item.quantity})"
    end
    message << "سعر التوصيل: #{delivery_price} دينار"
    message << "سعر الطلب كاملا: #{total_price} دينار"

    message << "موقع الزبون: https://maps.google.com?q=#{lat},#{lng}"
    
    return message.join("\n")
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController
  before_action :set_order, except: [:index]

  def index
     filter_orders
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to admin_orders_url, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def filter_orders
    @filter = params[:filter]
    if @filter.present?
      @orders = Order.send(@filter).order(created_at: :desc).page params[:page]
    else
      @orders = Order.order(created_at: :desc).page params[:page]
    end

  end
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find params[:id]
  end

  def order_params
    params.require(:order).permit(:id, :detail, :user_id, :order_cart_id, :status, :latitude, :longitude, :country, :mobile, :store_id)
  end
end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < StoreBaseController
  before_action :authenticate_user!, :check_authorization
  before_action :set_order, except: [:new, :index]
  respond_to :html

  def index 
    result = MarketPlace::Dashboard::Order.index(params[:status], @options)
    puts result[:orders_count]
    @orders_count = result[:orders_count]
    @pagy, @orders = pagy(result[:orders])
  end

  def edit
  end

  def update
    MarketPlace::Dashboard::Order.update(@order, order_params, @options)
    redirect_back(fallback_location: dashboard_orders_url)
    flash[:notice] = 'تم تعديل الطلب بنجاح'
  rescue MarketPlace::Errors::UnprocessableEntity
    render :edit
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = @current_store.orders.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:admin_detail, :status)
  end

end

app/controllers/orders_controller.rb
class OrdersController < StoreBaseController
  before_action :authenticate_user!, only: [:new, :create, :cancel, :index]
  before_action :set_order, only: [:show, :edit, :update, :destroy, :cancel]
  before_action :check_cart, only: [:new, :create]
  before_action :can_user_add_order?, only: [:new, :create]
  respond_to :html

  def index
    @pagy, @orders = pagy(MarketPlace::Order.index(params[:status], @options)[:orders])
  end

  def show
    render_not_found if !current_user || @order.user != current_user
  end

  def cancel
    @order.cancel_order
    redirect_to @order
  end

  def new
    @order = @current_store.orders.new
  end

  def create
    @order = @current_store.orders.new(order_params)
    respond_with MarketPlace::Order.create(@order, @options)[:order]
  rescue MarketPlace::Errors::UnprocessableEntity
    puts @order.errors
    render :new
  end

  private
  
  def set_order
    @order = Order.where(id: params[:id], store_id: @current_store.id, user_id: current_user.id).first
  end

  def check_cart
    if @cart.items.empty? || @cart.price < @current_store.min_order_total
      redirect_to cart_url
    end
  end

  def can_user_add_order?
    if !current_user.can_add_order?
      redirect_to cart_path
      flash[:alert] = "عذرا، قد تجاوزت الحد المسموح به للطلبات الجديدة"
    end
  end

  def order_params
    params.require(:order).permit(:detail, :location_id)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def print_order_status(status)
 	  case status
 	  when 'executing'
 	    t('order.print_status.executing')
 	  when 'completed'
 	    t('order.print_status.completed')
 	  when 'cancelled'
 	    t('order.print_status.cancelled')
 	  end
  end

  def print_orders_filter(status)
    case status
    when 'executing'
      "جارية التنفيذ"
    when 'completed'
      "المكتملة"
    when 'cancelled'
      "الملغاة"
    else
      "جميع الطلبات"
    end
  end

  def order_label_class(status)
    case status
    when 'executing'
      "primary"
    when 'completed'
      "success"
    when 'cancelled'
      "danger"
    else
      "جميع الطلبات"
    end
  end

end

app/views/admin/orders/_form.html.erb
<%= form_for([:admin, @order], html: { class: 'form-horizontal order' })  do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title"><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
      </div>
      <div class="panel-body">
        <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :detail, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :detail, class: 'form-control', disabled: 'disabled' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :user_id, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :user_id, class: 'form-control', disabled: 'disabled' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :latitude, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :latitude, class: 'form-control', disabled: 'disabled' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :longitude, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :longitude, class: 'form-control', disabled: 'disabled' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :admin_detail, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :admin_detail, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :status, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.select(:status, Order.statuses.keys.map {|status| [status.titleize,status]}) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :country, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.select(:country, Order.statuses.keys.map {|status| [status.titleize,status]}) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :order_cart_id, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :order_cart_id, class: 'form-control', disabled: 'disabled' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :store_id, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :store_id, class: 'form-control', disabled: 'disabled' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/orders/_order_item.erb
<ul class="list-unstyled">
  <% @order.order_items.each do |order_item| %>
    <li class="media-list">
      <div class="media">
        <div class="media-left">
          <%= image_tag order_item.product.image.url, class: "cat_img" %>
        </div>

        <div class="media-body">
          <div class="col-md-12">
            <h4><%= order_item.product.title %></h4>
          </div>
          <div class="col-md-3">
            Price: <%= order_item.product.price %>
          </div>
          <div class="col-md-3">
            quantity: <%= order_item.quantity %>
          </div>
          <div class="col-md-3">
            total_price: <%= order_item.total_price %>
          </div>
        </div>
      </div>
    </li>
    <hr>

  <% end %>
</ul>

app/views/admin/orders/edit.html.erb
<section class="content-header">
  <h1>
   Editing Order #<%= @order.id %>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= admin_root_path %>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="<%= admin_orders_path %>"><i class="fa fa-tags"></i> Orders</a></li>
    <li class="active">Editing Order #<%= @order.id %></li>
  </ol>
</section>


<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <%= render 'shared/bootstrap_alert' %>
      <div class="box">
        <div class="box-body">
          <%= render 'form' %>
        </div>
      </div>
    <%= link_to 'Show', admin_order_path(@order.id), class: 'btn btn-default' %>
    <%= link_to 'Back', admin_orders_path, class: 'btn btn-default' %>
    </div>
  </div>
</section>

app/views/admin/orders/index.html.erb
<section class="content-header">
  <h1>
    Orders
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= admin_root_path %>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Orders</li>
  </ol>
</section>


<section class="content">
  <!-- /.row -->
  <div class="row">
    <div class="col-xs-12">
      <%= render 'shared/bootstrap_alert' %>
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Orders Filter and Search </h3>

          <div class="box-tools">
            <form action="<%= admin_orders_path %>" method="GET">
              <div class="pull-left" style="margin-right: 10px;">
                <%= select_tag "filter", options_for_select([ "executing_orders", "completed_orders", "cancelled_orders" ], params[:filter] || "executing_orders"), class: 'form-control ', style: "height: 30px;" %> 
              </div>
              <div class="col-lg-5 input-group custom-search-form">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tbody>
              <tr>
                <th>Id</th>
                <th>User</th>
                <th>Status</th>
                <th>Total Price</th>
                <th></th>
              </tr>
              <% @orders.each do |order| %>
                <tr>
                  <td><%= link_to order.id, admin_order_path(order.id) %></td>
                  <td><%= order.user.fullname %></td>
                  <td><%= order.status %></td>
                  <td><%= order.total_price %></td>
                  <td>
                    <%= link_to 'Edit', edit_admin_order_path(order.id) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="text-center">
            <%= paginate @orders %>
          </div>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
  </div>
</section>

app/views/admin/orders/show.html.erb
<section class="content-header">
  <h1>
   New Page
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= admin_root_path %>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="<%= admin_pages_path %>"><i class="fa fa-tags"></i> Pages</a></li>
    <li class="active">New Page</li>
  </ol>
</section>


<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <%= render 'shared/bootstrap_alert' %>
      <div class="box">
        <div class="box-body">
          <div id="map"></div>

          <dl class="dl-horizontal">
            <dt><strong>Id:</strong></dt>
            <dd><%= @order.id %></dd>
          </dl>

          <dl class="dl-horizontal">
            <dt><strong>User:</strong></dt>
            <dd><%= @order.user.fullname %></dd>
          </dl>

          <dl class="dl-horizontal">
            <dt><strong>Detail:(User)</strong></dt>
            <dd><%= @order.detail %></dd>
          </dl>

          <dl class="dl-horizontal">
            <dt><strong>admin_detail:(Admin)</strong></dt>
            <dd><%= @order.admin_detail %></dd>
          </dl>

          <dl class="dl-horizontal">
            <dt><strong>delivery price:</strong></dt>
            <dd><%= @order.delivery_price %></dd>
          </dl>

          <dl class="dl-horizontal">
            <dt><strong>total price:</strong></dt>
            <dd><%= @order.total_price %></dd>
          </dl>

          <dl class="dl-horizontal">
            <dt><strong>Created at:</strong></dt>
            <dd><%= @order.created_at %></dd>
          </dl>

          <dl class="dl-horizontal">
            <dt><strong>Updated at:</strong></dt>
            <dd><%= @order.updated_at %></dd>
          </dl>


          <hr>

          <h1>Order OrderItems </h1>
          <%= render 'admin/orders/order_item' %>

        </div>
      </div>
    <%= link_to 'Edit', edit_admin_order_path(@order.id), class: 'btn btn-default' %>
    <%= link_to 'Back', admin_orders_path, class: 'btn btn-default' %>
    </div>
  </div>
</section>



<script type="text/javascript">
  var map;
  $(document).ready(
    function(){
      map = new GMaps({
        el: '#map',
        lat: <%= @order.lat %>,
        lng: <%= @order.lng %>
      });
      map.addMarker({
        lat: <%= @order.lat %>,
        lng: <%= @order.lng %>,
        title: "<%= @order.user.fullname %>",
        infoWindow: {
          content: "<p>رقم الطلب: #<%= @order.id %></p> <p>اسم المشتري: <%= @order.user.fullname %></p><p>رقم الجوال: <%= @order.user.mobile %></p>"
        }
      });
    }
  );
</script>