config/routes.rb
Rails.application.routes.draw do
  # move omniauth_callbacks devise module out the scope ':locale' when use it
  # devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  # use it when you add a new language to site
  # scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do

  constraints(RootStoreRoutes) do
    get '/', to: 'stores#show'
  end
  
  constraints(!RootStoreRoutes) do
    get '/', to: 'home#landing_page', as: :root
  end

  devise_for :users,
    controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
    },
    :path => "/",
    :path_names => { :sign_in =>       'login',
                     :sign_out =>      'logout',
                     :sign_up =>       '',
                     :registration =>  'register',
                     :edit =>          'profile',
                     :cancel =>        'cancel',
                     :confirmation =>  'verification'
                    }

  get "/profile", to: "users/registrations#edit", as: :profile
  put "/profile", to: "users/registrations#update"
  
  namespace :dashboard do
    root 'main#index', as: :dashboard
    get '/ajax/report', to: "main#report"

    resources :products, except: [:destroy]
    resources :pages, except: [:show, :destroy] do
      member do 
        put 'publish'
        put 'unpublish'
      end
    end

    resources :categories, except: [:show, :destroy] do
      member do 
        put 'hide'
        put 'unhide'
      end
    end

    resources :reviews, except: [:show, :destroy, :create] do
      member do 
        put 'hide'
        put 'unhide'
      end
    end

    resources :users, except: [:show, :destroy, :create] do 
      member do 
        put 'ban'
        put 'unban'
      end
    end
    resources :orders, except: [:destroy, :create]

    get :me, to: "users#me"
    put :me, to: "users#update_me" 

    scope :setup do 
      get :social_media, to: 'setup_stores#social_media'
      get :analytics,  to: 'setup_stores#analytics'
      get :details,  to: 'setup_stores#details'
      get :domain,  to: 'setup_stores#domain'
      get :seo,  to: 'setup_stores#seo'
      get :design, to: 'setup_stores#design'
      get :configuration, to: 'setup_stores#configuration'
      get :subscription, to: 'setup_stores#subscription'
      put :social_media, to: 'setup_stores#update_social_media'
      put :analytics, to: 'setup_stores#update_analytics'
      put :details, to: 'setup_stores#update_details'
      put :domain,  to: 'setup_stores#update_domain'
      put :seo,  to: 'setup_stores#update_seo'
      put :design, to: 'setup_stores#update_design'
      put :configuration, to: 'setup_stores#update_configuration'
      post :subscription, to: 'setup_stores#upgrade_subscription'
    end
  end

  # Sitemap
  resources :sitemap, only: [:index]
  
  resources :reviews
  resources :locations, except: [:show]
  resources :cart_items do
     member do 
      post 'decrease'
      post 'increase'
     end
  end
  
  resources :orders do 
    member do 
      put 'cancel'
    end
  end

  # Cart
  get 'cart' => "cart#index"

  # Search
  get '/search' => "search#search"

  # Contact Us 
  post '/p/contact-us', to: "contacts#create", as: :contact_us
  get '/p/contact-us', to: "contacts#new", as: :contacts

  # Dynamic pages
  get "/p/:slug", :to => "page#show"
  
  # Products
  get '/products/:category_slug/:id' => 'products#show', as: :product
  get '/products/:category_slug/' => 'products#index', as: :product_category
  get '/products' => 'products#index', as: :products

  # Favorites route
  post "products/:product_id/favorite" => "favorites#create", :as => :favorite
  delete "favorites/:product_id/destroy" => "favorites#destroy", :as => :destroy_favorite
  get '/favorites',to: "favorites#index",as: :favorites
  
  # admin
  namespace :admin do
    root 'dashboard#index'
    resources :users, except: [:destroy] do
      member do
        get :orders
        put :ban
        put :unban
      end
    end
    resources :categories, except: [:destroy]
    resources :products, except: [:destroy]
    resources :product_offers, except: [:destroy]
    resources :orders, only: [:index, :edit, :update, :show]
    resources :contacts, only: [:index]
    resources :pages, except: [:show]
    resources :reviews, only: [:index, :edit, :update]
  end

  # Errors 
  get "/404", :to => "errors#not_found"
  get "/403", :to => "errors#unavailable"
  get "/500", :to => "errors#internal_server_error"
  

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api/graphql"
  end

  # API 
  namespace :api do
    post "/graphql", to: "graphql#execute"
    post "/Settings.telegram.token" => 'telegram_bot#webhook'
  end

  # All paths with no locale specified will be redirected to the same paths with default locale
  #root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  #get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  #get '*path', :to => 'errors#not_found', via: :all
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminController
  def index
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_product, except: [:create, :new, :index]


  def index
    filter_products
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_url, notice: 'Product was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_products_url, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  private


  def filter_products
    @filter = params[:filter]
    if @filter.present?
      @products = Product.send(@filter).order(created_at: :desc).page params[:page]
    else
      @products = Product.order(created_at: :desc).page params[:page]
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find params[:id]
  end

  def product_params
    params.require(:product).permit(:id, :title, :description, :category_id, :price, :status, :in_stack)
  end
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < StoreBaseController
  before_action :authenticate_user!, :check_authorization
  before_action :set_category, except: [:create, :new, :index]
  respond_to :html

  def index
    @pagy, @categories = pagy(MarketPlace::Dashboard::Category.index(@options)[:categories])
  end

  def new
    @category = @current_store.categories.new
  end

  def edit
  end

  def create
    @category = @current_store.categories.new(category_params)
    MarketPlace::Dashboard::Category.create(@category, @options, flash)
    redirect_to dashboard_categories_url
  rescue MarketPlace::Errors::UnprocessableEntity
    render :new
  end

  def update
    MarketPlace::Dashboard::Category.update(@category, category_params, @options, flash)
    redirect_to dashboard_categories_url
  rescue MarketPlace::Errors::UnprocessableEntity
    render :edit
  end

  def hide
    @category.update(hidden: true)
  end

  def unhide
    @category.update(hidden: false)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = @current_store.categories.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:id, :name ,:slug, :image)
  end
end

app/controllers/dashboard/contacts_controller.rb
class Dashboard::ContactsController < ApplicationController
  
  def index
    @pagy, @contacts = pagy(@current_store.contacts.order(created_at: :desc))
  end

  def show
    @contact = @current_store.contacts.find(params[:id])
  end
end

app/controllers/dashboard/main_controller.rb
class Dashboard::MainController < StoreBaseController
  before_action :authenticate_user!, :check_authorization

  def index
    @report_hash = MarketPlace::Dashboard::Main.index(@options)[:report_hash]
  end

  def report
  	period = params[:period] || "all"
  	@report_hash = MarketPlace::Dashboard::Main.report(period, @options)[:report_hash]
  	respond_to :js
  end

end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < StoreBaseController
  before_action :authenticate_user!, :check_authorization
  before_action :set_order, except: [:new, :index]
  respond_to :html

  def index 
    result = MarketPlace::Dashboard::Order.index(params[:status], @options)
    puts result[:orders_count]
    @orders_count = result[:orders_count]
    @pagy, @orders = pagy(result[:orders])
  end

  def edit
  end

  def update
    MarketPlace::Dashboard::Order.update(@order, order_params, @options)
    redirect_back(fallback_location: dashboard_orders_url)
    flash[:notice] = 'تم تعديل الطلب بنجاح'
  rescue MarketPlace::Errors::UnprocessableEntity
    render :edit
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = @current_store.orders.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:admin_detail, :status)
  end

end

app/controllers/dashboard/pages_controller.rb
class Dashboard::PagesController < StoreBaseController
  before_action :authenticate_user!,
                :check_authorization,
                :set_page, only: [:edit, :update, :unpublish, :publish]

  def index
    @pages = @current_store.pages.order("created_at desc")
  end

  def new
    @page = @current_store.pages.new
  end

  def edit
    
  end

  def create
    @page = @current_store.pages.new(page_params)
    MarketPlace::Dashboard::Page.create(@page, @options)
    redirect_to dashboard_pages_url
    flash[:notice] = 'تم إضافة الصفحة بنجاح.'
  rescue MarketPlace::Errors::UnprocessableEntity
    render :new
  end

  def update
    MarketPlace::Dashboard::Page.update(@page, page_params, @options)
    redirect_to dashboard_pages_url
    flash[:notice] = 'تم تعديل الصفحة بنجاح'
  rescue MarketPlace::Errors::UnprocessableEntity
    render :edit
  end

  def publish
    @page.update(published: true)
  end

  def unpublish
    @page.update(published: false)
  end

  private

  def set_page
    @page = @current_store.pages.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:title, :slug, :meta_description, :meta_keywords, :content, :published)
  end

end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < StoreBaseController
  before_action :authenticate_user!, :check_authorization
  before_action :set_product, except: [:create, :new, :index]
  respond_to :html

  def index
    @pagy, @products = pagy(MarketPlace::Dashboard::Product.index(@options)[:products])
  end

  def new
    if @current_store.can_add_product?
      @product = @current_store.products.new
    else
      redirect_to dashboard_products_url
      flash[:alert] = 'لقد تجاوزت الحد المسموح به لإضافة منتجات جديدة'
    end
  end

  def edit
  end

  def create
    @product = @current_store.products.new(product_params)
    MarketPlace::Dashboard::Product.create(@product, @options)
    flash[:notice] = 'تم إضافة المنتج بنجاح.'
    redirect_to dashboard_products_url
  rescue MarketPlace::Errors::UnprocessableEntity
    render :new
  rescue MarketPlace::Errors::MaxProductsLimit
    flash[:alert] = 'لقد تجاوزت الحد المسموح به لإضافة منتجات ضمن الحساب المجاني'
    redirect_to dashboard_products_url
  end

  def update
    MarketPlace::Dashboard::Product.update(@product, product_params, @options)
    flash[:notice] = 'تم إضافة المنتج بنجاح.'
    redirect_to dashboard_products_url
  rescue MarketPlace::Errors::UnprocessableEntity
    render :edit
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = @current_store.products.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :category_id, :price, :status, :in_stack, :is_infinite, :new_category_name, :featured, images: [])
  end

end

app/controllers/dashboard/reviews_controller.rb
class Dashboard::ReviewsController < StoreBaseController
  before_action :authenticate_user!, :check_authorization
  before_action :set_review, only: [:edit, :hide, :unhide, :update]
  respond_to :html

  def index
    @pagy, @reviews = pagy(MarketPlace::Dashboard::Review.index(@options)[:reviews])
  end

  def edit
  end

  def update
    MarketPlace::Dashboard::Review.update(@review, review_params, @options)
    flash[:notice] = 'تم تعديل التقييم بنجاح.'
    redirect_to dashboard_reviews_url
  rescue MarketPlace::Errors::UnprocessableEntity
    render :edit
  end

  def hide
    @review.update(hidden: true)
  end

  def unhide
    @review.update(hidden: false)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = @current_store.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:id, :hidden, :content)
  end
end

app/controllers/dashboard/setup_stores_controller.rb
class Dashboard::SetupStoresController < StoreBaseController
  before_action :authenticate_user!, :check_authorization
  before_action :set_variable
  respond_to :html

  def show 
  end

  def social_media
  end

  def update_social_media
    update_store_attributes("social_media")
  end

  def analytics 
  end

  def update_analytics
    update_store_attributes("analytics")
  end

  def details
  end

  def update_details
    update_store_attributes("details")
    @current_store.update_setup_step("details")
  end

  def domain
  end

  def update_domain
    render_not_authorized unless @current_store.can_custom_domain?
    update_store_attributes("domain")
  end

  def seo
  end

  def update_seo
    update_store_attributes("seo")
  end

  def design
  end 

  def update_design
    if design_params.nil?
      flash[:error] = 'لم يتم تحديد مرفقات بعد.'
      redirect_back(fallback_location: dashboard_dashboard_path)
    else
      update_store_attributes("design")
      @current_store.update_setup_step("design")
    end
  end

  def configuration
  end

  def update_configuration
    update_store_attributes("configuration")
    @current_store.update_setup_step("configuration")
  end

  def subscription
  end

  def upgrade_subscription
    MarketPlace::Dashboard::Subscribe.upgrade(@options, subscription_params)
    @current_plan = @current_store.plan
  rescue MarketPlace::Errors::InvalidPaymentMethod
    @error = 'عذرا! الكوبون مستخدم او غير صالح.'
  rescue MarketPlace::Errors::InvalidCoupon
    @error = 'عذرا! الكوبون مستخدم او غير صالح.'
  rescue MarketPlace::Errors::EmptyCoupon
    @error = 'فارغ، يرجى ملء الحقل'
  end

  def dashboard
  end

  private 

  # Never trust parameters from the scary internet, only allow the white list through.
  def new_store_params
    params.require(:store).permit(:ident, users_attributes: [:email, :password, :password_confirmation, :fullname])
  end

  def social_media_params
    params.require(:store).permit(:ident)
  end

  def analytics_params
    params.require(:store).permit(:google_analytics_key)
  end

  def details_params
    params.require(:store).permit(:ident, :slogan, :description, :email, :mobile, :address)
  end

  def seo_params
    params.require(:store).permit(:meta_title, :meta_description)
  end

  def domain_params
    params.require(:store).permit(:domain, :use_domain)
  end

  def design_params
    params.require(:store).permit(:favicon, :logo, :cover_photo) rescue nil
  end

  def social_media_params
    params.require(:store).permit(:facebook, :twitter, :instagram)
  end

  def configuration_params
    params[:store].delete(:enable_google_maps) unless @current_store.can_use_google_map?
    params.require(:store).permit(:currency, :min_order_total, :enable_reviews, 
      :max_pending_order, :enable_google_maps, :delivery_start_at, 
      :delivery_end_at, :delivery_amount, :free_delivery_with_amount, :google_maps_key)
  end

  def subscription_params
    params.require(:store).permit(:coupon, :plan_duration, :plan_type, :payment_method)
  end

  def update_store_attributes(partial)
    if @current_store.update(send("#{partial}_params"))
      flash[:notice] = 'تم التحديث بنجاح'
      redirect_back(fallback_location: dashboard_dashboard_path)
    else
      render partial.to_sym
    end
  end

  def set_variable
    @setup_store_tab = true
  end

end

app/helpers/products_helper.rb
module ProductsHelper
  def print_product_status(status)
    case status
    when 'active'
      "<span>#{t('product.print_status.active')}</span>".html_safe
    when 'hidden'
      "<span>#{t('product.print_status.hidden')}</span>".html_safe
    end
  end
end

app/views/dashboard/products/_form.html.erb
<% submit_name = "إنشاء" %>
<% if action_name == "edit" %>
 <% submit_name = "تعديل" %>
 <% main_img = @product.images[0].variant(resize_to_limit: [1200, 800]) %>
  <div class="product_gallery">
    <div class="owl-carousel buttons-autohide controlls-over" data-plugin-options='{"singleItem": true, "navigation": true, "pagination": true, "transitionStyle":"fadeUp", "rtl": true}'>
      <% @product.images.each_with_index do |image, index| %>
        <div>
          <img class="img-responsive h-450" src="<%= url_for(image.variant(resize_to_limit: [1200, 800])) %>" alt="">
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<%= form_for([:dashboard, @product], html: { class: 'mb-0' } ) do |f| %>
  <div class="form-group <%= 'has-error' if @product.errors[:title].any? %>">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <small class="help-block <%= 'hidden' unless  @product.errors[:title].any? %>"><%= @product.errors[:title].first %></small>
  </div>

  <div class="form-group <%= 'has-error' if @product.errors[:slug].any? %>">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control textarea_editor', id: "textarea_editor" %>
    <small class="help-block <%= 'hidden' unless  @product.errors[:description].any? %>"><%= @product.errors[:description].first %></small>
  </div>

  <div class="row">
    <div class="col-md-6 col-xs-12">
      <div class="form-group <%= 'has-error' if @product.errors[:category_id].any? %>">
        <%= f.label :category_id %>
        <%= f.collection_select :category_id, @current_store.categories, :id, :name, {:include_blank => 'اختر تصنيف'},{:class => 'form-control'}  %>
        <small class="help-block <%= 'hidden' unless  @product.errors[:category_id].any? %>"><%= @product.errors[:category_id].first %></small>
      </div>
    </div>
    <div class="col-md-6 col-xs-12">
      <div class="form-group <%= 'has-error' if @product.errors[:category_id].any? %>">
        <%= f.label :new_category_name, "أو انشأ تصنيف جديد" %>
        <%= f.text_field :new_category_name, class: 'form-control' %>
      </div>
    </div>
  </div>
  
  <div class="form-group">
    <div class="row">
      <div class="col-md-6 col-xs-12">
        <%= f.label :in_stack %>
        <%= f.number_field :in_stack, class: 'form-control' %>
      </div>
      <div class="col-md-6 col-xs-12">
        <div class="checkbox-is_infinite pt-35">
          <%= f.label :is_infinite do %>
            <%= f.check_box :is_infinite %>
            غير محددة
          <% end %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="form-group <%= 'has-error' if @product.errors[:price].any? %>">
    <div class="row">
      <div class="col-md-6 col-xs-12">
        <%= f.label :price %>
        <%= f.number_field :price, class: 'form-control' %>
        <small class="help-block <%= 'hidden' unless  @product.errors[:price].any? %>"><%= @product.errors[:price].first %></small>
      </div>
      <div class="col-md-6 col-xs-12">
      </div>
   
    </div>
  </div>

  <div class="form-group <%= 'has-error' if @product.errors[:images].any? %>">
    <%= f.label :images %>
    <div class="input-group">
      <label class="input-group-btn">
        <span class="btn btn-primary">
          تصفح <i class="fa fa-upload"></i>
          <%= f.file_field :images, multiple: true, class: "hidden products-images" %>
        </span>
      </label>
      <input type="text" class="form-control upload-info" readonly>
    </div>
    <small class="help-block <%= 'hidden' unless  @product.errors[:images].any? %>"><%= @product.errors[:images].first %></small>
  </div>

  <div id="photos" class="row m-0"></div>

  <div class="form-group">
    <%= f.label :featured do %>
      <%= f.check_box :featured %>
      اجعل هذه المنتج مميز واعرضه بالرئيسية
    <% end %>
  </div>

  <div class="clearfix">
    <%= f.button submit_name, class: "btn btn-primary pull-right", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> #{submit_name} ..."} %>
  </div>
<% end %>

app/views/dashboard/products/_product.html.erb
<tr id="product-<%= product.id %>">
   <td class="hidden-xs">
     <% if product.images.attached? %>
       <%= image_tag url_for(product.images[0].variant(resize_to_limit: [80, 80])), class: "small-thumbail"%>
     <% end %>
   </td>
   <td class="details-td">
      <h3 class="details-head">
        <%= link_to product.title, product.url %>
      </h3>
      <ul class="details-list">
         <li><i class="fa fa-fw fa-bookmark"></i> <span> <%= product.id %></span> </li>
        <li><i class="fa fa-fw fa-tag"></i><span><%= product.category.name if product.category  %></span> </li>
        <li><i class="fa fa-fw fa-money"></i> <span><%= product.price %></span></li>
        <% unless product.status %>
          <li><i class="fa fa-fw fa-eye-slash"></i> <span> <%= print_product_status(product.status) %></span> </li>
        <% end %>
      </ul>
   </td>

   <td>
     <div class="pull-left">
       <div class="dropdown btn-group pull-left">
           <button class="dropdown-toggle btn btn-default btn-sm" data-toggle="dropdown">
               <i class="fa fa-gear"></i>
               <span class="hidden-xs"> خيارات</span>
               <i class="fa fa-caret-down"></i>
             </button>
           
           <ul class="dropdown-menu dropdown-left dropdown-menu-left" role="menu" aria-labelledby="خيارات المستخدم">
              <li>
                <%= link_to  edit_dashboard_product_path(product.id) do %>
                  <i class="fa fa-pencil"></i>
                  <span class="action-text">تعديل المنتج</span>
                <% end %>
              </li>
           </ul>
       </div>
     </div>
   </td>
</tr>

app/views/dashboard/products/edit.html.erb
<% title 'تعديل المنتج' %>

<section>
  <div class="container">
    <div class="row">
      <!-- Sidebar -->
      <%= render 'dashboard/shared/sidebar' %>

      <!-- LEFT -->
      <div class="col-lg-9 col-md-8 col-sm-8">
        <div class="white-block">
          <h3>تعديل المنتج</h3>
            <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- / -->

app/views/dashboard/products/index.html.erb
<% title t('header.shop') %>
<section>
<div class="container">
  <div class="row">
    <!-- Sidebar -->
    <%= render 'dashboard/shared/sidebar' %>
    <!-- LEFT -->
    <div class="col-lg-9 col-md-8 col-sm-8">
      <div class="bg-white">
        <h3 class="p-20">المنتجات (<span><%= @current_store.products.count %></span>)
          <%= link_to 'منتج جديد', new_dashboard_product_path, class: 'btn btn-primary btn-sm pull-left' %>
        </h3>
          <table id="products_table">
            <colgroup>
              <col class="col-lg-1 hidden-xs"> 
              <col class="col-lg-8"> 
              <col class="col-lg-3">
            </colgroup>
            <tbody>
              <%= render partial: "dashboard/products/product", collection: @products %>
            </tbody>
          </table>


          <div class="text-center">
            <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
          </div>
      </div>
    </div>
  </div>
</div>
</section>
<!-- / -->

app/views/dashboard/products/new.html.erb
<% title 'منتج جديد' %>

<section>
  <div class="container">
    <div class="row">
      <!-- Sidebar -->
      <%= render 'dashboard/shared/sidebar' %>

      <!-- LEFT -->
      <div class="col-lg-9 col-md-8 col-sm-8">
        <div class="white-block">
          <h3>منتج جديد</h3>
            <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- / -->