config/routes.rb
Rails.application.routes.draw do
  # move omniauth_callbacks devise module out the scope ':locale' when use it
  # devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  # use it when you add a new language to site
  # scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do

  constraints(RootStoreRoutes) do
    get '/', to: 'stores#show'
  end
  
  constraints(!RootStoreRoutes) do
    get '/', to: 'home#landing_page', as: :root
  end

  devise_for :users,
    controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
    },
    :path => "/",
    :path_names => { :sign_in =>       'login',
                     :sign_out =>      'logout',
                     :sign_up =>       '',
                     :registration =>  'register',
                     :edit =>          'profile',
                     :cancel =>        'cancel',
                     :confirmation =>  'verification'
                    }

  get "/profile", to: "users/registrations#edit", as: :profile
  put "/profile", to: "users/registrations#update"
  
  namespace :dashboard do
    root 'main#index', as: :dashboard
    get '/ajax/report', to: "main#report"

    resources :products, except: [:destroy]
    resources :pages, except: [:show, :destroy] do
      member do 
        put 'publish'
        put 'unpublish'
      end
    end

    resources :categories, except: [:show, :destroy] do
      member do 
        put 'hide'
        put 'unhide'
      end
    end

    resources :reviews, except: [:show, :destroy, :create] do
      member do 
        put 'hide'
        put 'unhide'
      end
    end

    resources :users, except: [:show, :destroy, :create] do 
      member do 
        put 'ban'
        put 'unban'
      end
    end
    resources :orders, except: [:destroy, :create]

    get :me, to: "users#me"
    put :me, to: "users#update_me" 

    scope :setup do 
      get :social_media, to: 'setup_stores#social_media'
      get :analytics,  to: 'setup_stores#analytics'
      get :details,  to: 'setup_stores#details'
      get :domain,  to: 'setup_stores#domain'
      get :seo,  to: 'setup_stores#seo'
      get :design, to: 'setup_stores#design'
      get :configuration, to: 'setup_stores#configuration'
      get :subscription, to: 'setup_stores#subscription'
      put :social_media, to: 'setup_stores#update_social_media'
      put :analytics, to: 'setup_stores#update_analytics'
      put :details, to: 'setup_stores#update_details'
      put :domain,  to: 'setup_stores#update_domain'
      put :seo,  to: 'setup_stores#update_seo'
      put :design, to: 'setup_stores#update_design'
      put :configuration, to: 'setup_stores#update_configuration'
      post :subscription, to: 'setup_stores#upgrade_subscription'
    end
  end

  # Sitemap
  resources :sitemap, only: [:index]
  
  resources :reviews
  resources :locations, except: [:show]
  resources :cart_items do
     member do 
      post 'decrease'
      post 'increase'
     end
  end
  
  resources :orders do 
    member do 
      put 'cancel'
    end
  end

  # Cart
  get 'cart' => "cart#index"

  # Search
  get '/search' => "search#search"

  # Contact Us 
  post '/p/contact-us', to: "contacts#create", as: :contact_us
  get '/p/contact-us', to: "contacts#new", as: :contacts

  # Dynamic pages
  get "/p/:slug", :to => "page#show"
  
  # Products
  get '/products/:category_slug/:id' => 'products#show', as: :product
  get '/products/:category_slug/' => 'products#index', as: :product_category
  get '/products' => 'products#index', as: :products

  # Favorites route
  post "products/:product_id/favorite" => "favorites#create", :as => :favorite
  delete "favorites/:product_id/destroy" => "favorites#destroy", :as => :destroy_favorite
  get '/favorites',to: "favorites#index",as: :favorites
  
  # admin
  namespace :admin do
    root 'dashboard#index'
    resources :users, except: [:destroy] do
      member do
        get :orders
        put :ban
        put :unban
      end
    end
    resources :categories, except: [:destroy]
    resources :products, except: [:destroy]
    resources :product_offers, except: [:destroy]
    resources :orders, only: [:index, :edit, :update, :show]
    resources :contacts, only: [:index]
    resources :pages, except: [:show]
    resources :reviews, only: [:index, :edit, :update]
  end

  # Errors 
  get "/404", :to => "errors#not_found"
  get "/403", :to => "errors#unavailable"
  get "/500", :to => "errors#internal_server_error"
  

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api/graphql"
  end

  # API 
  namespace :api do
    post "/graphql", to: "graphql#execute"
    post "/Settings.telegram.token" => 'telegram_bot#webhook'
  end

  # All paths with no locale specified will be redirected to the same paths with default locale
  #root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  #get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  #get '*path', :to => 'errors#not_found', via: :all
end

app/models/product_offer.rb
# == Schema Information
#
# Table name: product_offers
#
#  id                     :integer          not null, primary key
#  product_id             :integer
#  start_at               :datetime
#  end_at                 :datetime
#  active                 :boolean          default: true
#  price                  :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null

class ProductOffer < ApplicationRecord
  belongs_to :product

  validates_uniqueness_of :product_id
  validates :price, numericality: { only_integer: true }
  validates_presence_of :start_at, :end_at
  
  def active?
    active 
  end
end

app/controllers/admin/product_offers_controller.rb
class Admin::ProductOffersController < Admin::AdminController
  before_action :set_offer, except: [:create, :new, :index]


  def index
    @offers = ProductOffer.all.order("created_at desc").page params[:page]
  end

  def new
    @offer = ProductOffer.new
  end

  def edit
  end

  def create
    @offer = ProductOffer.new(product_params)
    respond_to do |format|
      if @offer.save
        format.html { redirect_to admin_product_offers_url, notice: 'Offer was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: 'new' }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @offer.update(product_params)
        format.html { redirect_to admin_product_offers_url, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  private


  def filter_products
    @filter = params[:filter]
    if @filter.present?
      @products = Product.send(@filter).order(created_at: :desc).page params[:page]
    else
      @products = Product.order(created_at: :desc).page params[:page]
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_offer
    @offer = ProductOffer.find params[:id]
  end

  def product_params
    params.require(:product_offer).permit(:id, :product_id, :start_at ,:end_at, :price, :active)
  end
end

app/views/admin/product_offers/_form.html.erb
<%= form_for([:admin, @offer], html: { class: 'form-horizontal offer' } ) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title"><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>
      </div>
      <div class="panel-body">
        <ul>
        <% @offer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
  <% @offers = ProductOffer.all.pluck(:product_id) %>
  <% @products = Product.where.not(id: @offers) %>
  
  <% if action_name == "edit"  %>
    <div class="form-group">
      <%= f.label :product_id ,class: 'control-label col-md-2' %>
      <div class="col-md-10">
      <%= f.text_field :product_id,class: "form-control", disabled: true %>
      </div>
    </div>
  <% else %>
    <div class="form-group">
      <%= f.label :product_id ,class: 'control-label col-md-2' %>
      <div class="col-md-10">
      <%= f.select(:product_id, @products.collect {|p| [ p.ar_name, p.id ] }, {include_blank: true}, { class: "chosen-select form-control" })%>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :start_at ,class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select(:start_at, :default => { :hour => 23, :minute => 59 } ) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_at, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select(:end_at, :default => { :hour => 23, :minute => 59 } ) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :price, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :active, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :active %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/product_offers/edit.html.erb
<section class="content-header">
  <h1>
    Editing Offer #<%= @offer.id %>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= admin_root_path %>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="<%= admin_product_offers_path %>"><i class="fa fa-tags"></i> Offers</a></li>
    <li class="active">Editing #<%= @offer.id %></li>
  </ol>
</section>


<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <%= render 'shared/bootstrap_alert' %>
      <div class="box">
        <div class="box-body">
          <div class="box-body table-responsive">
            <table class="table table-hover">
                <tbody>
                  <tr>
                    <th>Image</th>
                    <th>Product Name</th>
                    <th>price</th>
                  </tr>
                    <tr>
                      <% if @offer.product.image.url %>
                         <td><%= image_tag @offer.product.image.small.url, class: "cat_img"  %></td>
                      <% else %>
                         <td></td>
                      <% end %>
                      <td><%= link_to @offer.product.ar_name, edit_admin_product_path(@offer.product) %></td>
                      <td><%= @offer.product.price %></td>
                    </tr>
                </tbody>
            </table>
          </div> 
        </div>
      </div>
      <div class="box">
        <div class="box-body">
          <%= render 'form' %>
        </div>
      </div>
    <%= link_to 'Back', admin_product_offers_path, class: 'btn btn-default' %>
    </div>
  </div>
</section>

app/views/admin/product_offers/index.html.erb
<section class="content-header">
  <h1>
    Offers
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= admin_root_path %>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Offers</li>
  </ol>
</section>


<section class="content">
  <!-- /.row -->
  <div class="row">
    <div class="col-xs-12">
      <%= render 'shared/bootstrap_alert' %>
      <div class="box">
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tbody>
              <tr>
                <th>Image</th>
                <th>Product Name</th>
                <th>Price</th>
                <th>Start_at</th>
                <th>End_at</th>
                <th>Active</th>
                <th></th>
              </tr>
              <% @offers.each do |offer| %>
                <tr>
                  <% if offer.product.image.url %>
                     <td><%= image_tag offer.product.image.small.url, class: "cat_img"  %></td>
                  <% else %>
                     <td></td>
                  <% end %>
                  <td><%= link_to offer.product.ar_name, edit_admin_product_path(offer.product) %></td>
                  <td><%= offer.price %></td>
                  <td><%= offer.start_at.strftime("%F") %></td>
                  <td><%= offer.end_at.strftime("%F") %></td>
                  <td><span class="label <%= offer.active ? 'bg-green' : 'bg-red' %>"><%= offer.active %></span></td>
                  <td>
                    <%= link_to "Edit", edit_admin_product_offer_path(offer.id) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="text-center">
            <%= paginate @offers %>
          </div>

        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
      <%= link_to 'New Offer', new_admin_product_offer_path, class: 'btn btn-default' %>

    </div>
  </div>
</section>

app/views/admin/product_offers/new.html.erb
<section class="content-header">
  <h1>
    New Category
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= admin_root_path %>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="<%= admin_categories_path %>"><i class="fa fa-tags"></i> Categories</a></li>
    <li class="active">New Category</li>
  </ol>
</section>


<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <%= render 'shared/bootstrap_alert' %>
      <div class="box">
        <div class="box-body">
          <%= render 'form' %>
        </div>
      </div>
    <%= link_to 'Back', admin_categories_path, class: 'btn btn-default' %>
    </div>
  </div>
</section>